#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'oscope_status', class 'altera_avalon_pio'
 * The macros are prefixed with 'OSCOPE_STATUS_'.
 * The prefix is the slave descriptor.
 */
#define OSCOPE_STATUS_COMPONENT_TYPE altera_avalon_pio
#define OSCOPE_STATUS_COMPONENT_NAME oscope_status
#define OSCOPE_STATUS_BASE 0x0
#define OSCOPE_STATUS_SPAN 16
#define OSCOPE_STATUS_END 0xf
#define OSCOPE_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define OSCOPE_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define OSCOPE_STATUS_CAPTURE 0
#define OSCOPE_STATUS_DATA_WIDTH 32
#define OSCOPE_STATUS_DO_TEST_BENCH_WIRING 0
#define OSCOPE_STATUS_DRIVEN_SIM_VALUE 0
#define OSCOPE_STATUS_EDGE_TYPE NONE
#define OSCOPE_STATUS_FREQ 50000000
#define OSCOPE_STATUS_HAS_IN 1
#define OSCOPE_STATUS_HAS_OUT 0
#define OSCOPE_STATUS_HAS_TRI 0
#define OSCOPE_STATUS_IRQ_TYPE NONE
#define OSCOPE_STATUS_RESET_VALUE 1023

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1581673437

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'channel_2_mem', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'CHANNEL_2_MEM_'.
 * The prefix is the slave descriptor.
 */
#define CHANNEL_2_MEM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define CHANNEL_2_MEM_COMPONENT_NAME channel_2_mem
#define CHANNEL_2_MEM_BASE 0x20000
#define CHANNEL_2_MEM_SPAN 51199
#define CHANNEL_2_MEM_END 0x2c7ff
#define CHANNEL_2_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define CHANNEL_2_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define CHANNEL_2_MEM_CONTENTS_INFO ""
#define CHANNEL_2_MEM_DUAL_PORT 1
#define CHANNEL_2_MEM_GUI_RAM_BLOCK_TYPE AUTO
#define CHANNEL_2_MEM_INIT_CONTENTS_FILE soc_system_channel_2_mem
#define CHANNEL_2_MEM_INIT_MEM_CONTENT 0
#define CHANNEL_2_MEM_INSTANCE_ID NONE
#define CHANNEL_2_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define CHANNEL_2_MEM_RAM_BLOCK_TYPE AUTO
#define CHANNEL_2_MEM_READ_DURING_WRITE_MODE DONT_CARE
#define CHANNEL_2_MEM_SINGLE_CLOCK_OP 0
#define CHANNEL_2_MEM_SIZE_MULTIPLE 1
#define CHANNEL_2_MEM_SIZE_VALUE 51199
#define CHANNEL_2_MEM_WRITABLE 1
#define CHANNEL_2_MEM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define CHANNEL_2_MEM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define CHANNEL_2_MEM_MEMORY_INFO_GENERATE_HEX 1
#define CHANNEL_2_MEM_MEMORY_INFO_HAS_BYTE_LANE 0
#define CHANNEL_2_MEM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define CHANNEL_2_MEM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 8
#define CHANNEL_2_MEM_MEMORY_INFO_MEM_INIT_FILENAME soc_system_channel_2_mem

/*
 * Macros for device 'channel_1_mem', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'CHANNEL_1_MEM_'.
 * The prefix is the slave descriptor.
 */
#define CHANNEL_1_MEM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define CHANNEL_1_MEM_COMPONENT_NAME channel_1_mem
#define CHANNEL_1_MEM_BASE 0x40000
#define CHANNEL_1_MEM_SPAN 51199
#define CHANNEL_1_MEM_END 0x4c7ff
#define CHANNEL_1_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define CHANNEL_1_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define CHANNEL_1_MEM_CONTENTS_INFO ""
#define CHANNEL_1_MEM_DUAL_PORT 1
#define CHANNEL_1_MEM_GUI_RAM_BLOCK_TYPE AUTO
#define CHANNEL_1_MEM_INIT_CONTENTS_FILE soc_system_channel_1_mem
#define CHANNEL_1_MEM_INIT_MEM_CONTENT 0
#define CHANNEL_1_MEM_INSTANCE_ID NONE
#define CHANNEL_1_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define CHANNEL_1_MEM_RAM_BLOCK_TYPE AUTO
#define CHANNEL_1_MEM_READ_DURING_WRITE_MODE DONT_CARE
#define CHANNEL_1_MEM_SINGLE_CLOCK_OP 0
#define CHANNEL_1_MEM_SIZE_MULTIPLE 1
#define CHANNEL_1_MEM_SIZE_VALUE 51199
#define CHANNEL_1_MEM_WRITABLE 1
#define CHANNEL_1_MEM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define CHANNEL_1_MEM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define CHANNEL_1_MEM_MEMORY_INFO_GENERATE_HEX 1
#define CHANNEL_1_MEM_MEMORY_INFO_HAS_BYTE_LANE 0
#define CHANNEL_1_MEM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define CHANNEL_1_MEM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 8
#define CHANNEL_1_MEM_MEMORY_INFO_MEM_INIT_FILENAME soc_system_channel_1_mem


#endif /* _ALTERA_HPS_0_H_ */
